### PR TITLE
Split Performance Numbers for Lurk

### PR DESCRIPTION
**Pull request by Robertorosmaninho**
Splitting GPU time in: Execution +Prove | Verify | Prove + Verify

Unfortunately, afaik is impossible to split between execution time and prove time in Lurk.
Due to the known issue of not being able to execute Lurk only in the CPU when GPU is available, we can't update the numbers regarding CPU execution using the same machine.

### CODE REVIEW

**Review by yzhang90 — DISMISSED** [review]
LGTM

**Review by yzhang90 — APPROVED** [review]
LGTM

**Comment by Robertorosmaninho** [comment]
@yzhang90 could you please add a new column with the total time? (Prove+verify)

**Comment by yzhang90** [comment]
> @yzhang90 could you please add a new column with the total time? (Prove+verify)

done

**Pull request merged**
